package com.jmojtest.demo.dataobject;

public class JudgetestDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgetest.test_id
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgetest.content
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgetest.questionid
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    private String questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgetest.answer
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgetest.test_id
     *
     * @return the value of judgetest.test_id
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgetest.test_id
     *
     * @param testId the value for judgetest.test_id
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgetest.content
     *
     * @return the value of judgetest.content
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgetest.content
     *
     * @param content the value for judgetest.content
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgetest.questionid
     *
     * @return the value of judgetest.questionid
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public String getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgetest.questionid
     *
     * @param questionid the value for judgetest.questionid
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public void setQuestionid(String questionid) {
        this.questionid = questionid == null ? null : questionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgetest.answer
     *
     * @return the value of judgetest.answer
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgetest.answer
     *
     * @param answer the value for judgetest.answer
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}