package com.jmojtest.demo.dataobject;

public class SubmissionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.idsub
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private String idsub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.email
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.problemid
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private Integer problemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.if_compile
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private Integer ifCompile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.if_pass
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private Integer ifPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.time_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private Integer timeUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission.memory_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    private Integer memoryUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.idsub
     *
     * @return the value of submission.idsub
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public String getIdsub() {
        return idsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.idsub
     *
     * @param idsub the value for submission.idsub
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setIdsub(String idsub) {
        this.idsub = idsub == null ? null : idsub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.email
     *
     * @return the value of submission.email
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.email
     *
     * @param email the value for submission.email
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.problemid
     *
     * @return the value of submission.problemid
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public Integer getProblemid() {
        return problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.problemid
     *
     * @param problemid the value for submission.problemid
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setProblemid(Integer problemid) {
        this.problemid = problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.if_compile
     *
     * @return the value of submission.if_compile
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public Integer getIfCompile() {
        return ifCompile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.if_compile
     *
     * @param ifCompile the value for submission.if_compile
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setIfCompile(Integer ifCompile) {
        this.ifCompile = ifCompile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.if_pass
     *
     * @return the value of submission.if_pass
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public Integer getIfPass() {
        return ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.if_pass
     *
     * @param ifPass the value for submission.if_pass
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setIfPass(Integer ifPass) {
        this.ifPass = ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.time_used
     *
     * @return the value of submission.time_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public Integer getTimeUsed() {
        return timeUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.time_used
     *
     * @param timeUsed the value for submission.time_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setTimeUsed(Integer timeUsed) {
        this.timeUsed = timeUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission.memory_used
     *
     * @return the value of submission.memory_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public Integer getMemoryUsed() {
        return memoryUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission.memory_used
     *
     * @param memoryUsed the value for submission.memory_used
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    public void setMemoryUsed(Integer memoryUsed) {
        this.memoryUsed = memoryUsed;
    }
}