package com.jmojtest.demo.dao;

import com.jmojtest.demo.dataobject.JudgetestDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface JudgetestDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    int deleteByPrimaryKey(String testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    int insert(JudgetestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    int insertSelective(JudgetestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    JudgetestDO selectByPrimaryKey(String testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    int updateByPrimaryKeySelective(JudgetestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgetest
     *
     * @mbg.generated Tue Aug 25 04:40:23 AEST 2020
     */
    int updateByPrimaryKey(JudgetestDO record);

    String selecttestcase(String idquestion);
    String selectanswer(String idquestion);
}