package com.jmojtest.demo.dao;

import com.jmojtest.demo.dataobject.SubmissionDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SubmissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    int deleteByPrimaryKey(String idsub);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    int insert(SubmissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    int insertSelective(SubmissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    SubmissionDO selectByPrimaryKey(String idsub);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    int updateByPrimaryKeySelective(SubmissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submission
     *
     * @mbg.generated Tue Aug 25 03:52:02 AEST 2020
     */
    int updateByPrimaryKey(SubmissionDO record);

    SubmissionDO selectbySID(String idsub);

    void insertSubid(String idsub,int problemid,int ifCompile,int ifPass,int timeUsed,int memoryUsed,String email);

    void updateifcompile(int ifCompile,String idsub);

    void updateifpass(int ifPass,String idsub);

    void updatetime(int timeUsed,String idsub);

    void updatememory(int memoryUsed,String idsub);
}